import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Nav";
import Glossary from "../components/Glossary";
import Table from "../components/Table";
import Selector from "../components/Selector";

const name = "[Oscar Loaiza]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Emtelco | Oscar Loaiza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <Selector />
        <Glossary />
        <Table />
      </body>
    </html>
  );
}
